apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: medical-analyzer
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: db-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
